<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AudioFiles\Alarm.wav" />
    <None Remove="DetectionTypes\face_detection_yunet_2026may.onnx" />
    <None Remove="DetectionTypes\shape_predictor_68_face_landmarks.dat" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AudioFiles\Alarm.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DetectionTypes\face_detection_yunet_2026may.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DetectionTypes\shape_predictor_68_face_landmarks.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DlibDotNet" Version="19.21.0.20220724" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\publish.yml" />
  </ItemGroup>

</Project>
